[build]
command = "ng build --configuration production"
publish = "dist/my-bio-app"

[[plugins]]
package = "@netlify/angular-runtime"
# Disable this plugin explicitly
[plugins.inputs]
disabled = true
